<?php
/* The Configuration File - Be careful while editing */
return array(
  'db' => array(
    'type' => 'sqlite',
    'path' => '/contents/extra/lobby_db.sqlite',
    'prefix' => 'l_'
  ),
  /**
   * The GLOBAL unique ID of YOUR Lobby installation
   */
  'lobbyID' => 'iFqEHfeto85vtbaHjqKI8uPNib0fzW1HsicZngjCeeXyg',
  /**
   * A Secure Identity of YOUR Lobby Installation.
   * Never reveal it TO ANYONE
   */
  'secureID' => '0caad5b01ff09c5d53355e560ef45477ae9291d49ff963cae1320e95d117b4066c700e091d6302e6c30753fb91385585b40c1a1485e76211e0fe1743cc052cb9',
  'debug' => false
);
/* DO NOT EDIT THIS FILE IF YOU DON'T KNOW WHAT YOU'RE DOING - Subin */
?>
